spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/database_products
    username: postgres
    password: leandro

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show-sql: true
